[package]
name = "lessons"
version = "0.1.0"
edition = "2021"
authors = ["Andrzej Głuszak", "Piotr Wojtczak"]

[[bin]]
name = "1_errors_demo"
path = "content/lessons/1_introduction/errors_demo.rs"
[[bin]]
name = "1_hello_world"
path = "content/lessons/1_introduction/hello_world.rs"
[[bin]]
name = "1_conditionals"
path = "content/lessons/1_introduction/conditionals.rs"
[[bin]]
name = "1_functions"
path = "content/lessons/1_introduction/functions.rs"
[[bin]]
name = "1_loops"
path = "content/lessons/1_introduction/loops.rs"
[[bin]]
name = "1_variables"
path = "content/lessons/1_introduction/variables.rs"
[[bin]]
name = "3_data_types"
path = "content/lessons/3_data_types/data_types.rs"
[[bin]]
name = "4_enums"
path = "content/lessons/4_enums/enums.rs"
[[bin]]
name = "4_option"
path = "content/lessons/4_enums/option.rs"
[[bin]]
name = "4_pattern_matching"
path = "content/lessons/4_enums/pattern_matching.rs"
[[bin]]
name = "4_result"
path = "content/lessons/4_enums/result.rs"
[[bin]]
name = "5_test"
path = "content/lessons/5_tests/test.rs"
[[bin]]
name = "6_basic_traits"
path = "content/lessons/6_types_reasoning/basic_trait.rs"
[[bin]]
name = "6_generic_largest"
path = "content/lessons/6_types_reasoning/generic_largest.rs"
[[bin]]
name = "6_generics"
path = "content/lessons/6_types_reasoning/generics.rs"
[[bin]]
name = "6_non_generic"
path = "content/lessons/6_types_reasoning/non_generic.rs"
[[bin]]
name = "6_trait_default"
path = "content/lessons/6_types_reasoning/trait_default.rs"
[[bin]]
name = "6_lifetimes_basic"
path = "content/lessons/6_types_reasoning/lifetimes_basic.rs"
[[bin]]
name = "6_lifetimes_elision"
path = "content/lessons/6_types_reasoning/lifetimes_elision.rs"
[[bin]]
name = "6_generic_fun"
path = "content/lessons/6_types_reasoning/generics_fun.rs"
[dependencies]
rand = "0.8"
