[package]
name = "lessons"
version = "0.1.0"
edition = "2021"
authors = ["Andrzej Głuszak", "Piotr Wojtczak"]

[[bin]]
name = "1_errors_demo"
path = "content/lessons/1_introduction/errors_demo.rs"
[[bin]]
name = "1_hello_world"
path = "content/lessons/1_introduction/hello_world.rs"
[[bin]]
name = "1_conditionals"
path = "content/lessons/1_introduction/conditionals.rs"
[[bin]]
name = "1_functions"
path = "content/lessons/1_introduction/functions.rs"
[[bin]]
name = "1_loops"
path = "content/lessons/1_introduction/loops.rs"
[[bin]]
name = "1_variables"
path = "content/lessons/1_introduction/variables.rs"
[[bin]]
name = "3_data_types"
path = "content/lessons/3_data_types/data_types.rs"
[[bin]]
name = "4_enums"
path = "content/lessons/4_enums/enums.rs"
[[bin]]
name = "4_option"
path = "content/lessons/4_enums/option.rs"
[[bin]]
name = "4_pattern_matching"
path = "content/lessons/4_enums/pattern_matching.rs"
[[bin]]
name = "4_result"
path = "content/lessons/4_enums/result.rs"
[[bin]]
name = "5_test"
path = "content/lessons/5_tests/test.rs"

[dependencies]
rand = "0.8"

